# Generated by Django 5.2.17 on 2026-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auth_policy_site_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authpolicy',
            options={'verbose_name': '인증 정책', 'verbose_name_plural': '인증 정책'},
        ),
        migrations.AlterModelOptions(
            name='ssoprovider',
            options={'ordering': ('position', 'id'), 'verbose_name': 'SSO 제공자', 'verbose_name_plural': 'SSO 제공자'},
        ),
        migrations.AlterField(
            model_name='authpolicy',
            name='allow_new_registrations',
            field=models.BooleanField(default=True, verbose_name='회원 가입 허용'),
        ),
        migrations.AlterField(
            model_name='authpolicy',
            name='api_tokens_enabled',
            field=models.BooleanField(default=True, verbose_name='API 토큰 인증 허용'),
        ),
        migrations.AlterField(
            model_name='authpolicy',
            name='password_login_enabled',
            field=models.BooleanField(default=True, verbose_name='비밀번호 로그인 허용'),
        ),
        migrations.AlterField(
            model_name='authpolicy',
            name='public_pins_enabled',
            field=models.BooleanField(default=True, verbose_name='비로그인 Pin 보기'),
        ),
        migrations.AlterField(
            model_name='authpolicy',
            name='recovery_allowed_cidrs',
            field=models.JSONField(blank=True, default=list, verbose_name='복구 허용 CIDR'),
        ),
        migrations.AlterField(
            model_name='authpolicy',
            name='recovery_denied_cidrs',
            field=models.JSONField(blank=True, default=list, verbose_name='복구 차단 CIDR'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='allow_signup',
            field=models.BooleanField(default=False, verbose_name='신규 SSO 사용자 가입 허용'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='allowed_endpoint_origins',
            field=models.JSONField(blank=True, default=list, verbose_name='허용 endpoint origin'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='discovery_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='Discovery URL'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='internal_cidrs',
            field=models.JSONField(blank=True, default=list, verbose_name='내부 IdP 허용 CIDR'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='issuer',
            field=models.URLField(blank=True, max_length=2048, verbose_name='발급자'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='kind',
            field=models.CharField(choices=[('authentik', 'Authentik'), ('synology', 'Synology SSO Server'), ('google', 'Google'), ('microsoft', 'Microsoft'), ('github', 'GitHub'), ('oidc', '범용 OIDC')], max_length=20, verbose_name='제공자 종류'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='name',
            field=models.CharField(max_length=150, verbose_name='표시 이름'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='표시 순서'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='public_base_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='공개 서비스 기준 URL'),
        ),
        migrations.AlterField(
            model_name='ssoprovider',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Microsoft 테넌트 UUID'),
        ),
    ]
