# Generated by Django 2.2.14 on 2026-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210311_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
