# Generated by Django 2.2.28 on 2026-08-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0011_pin_trashed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchImportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField()),
                ('client_item_id', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('retryable', models.NullBooleanField()),
                ('lease_uuid', models.UUIDField(blank=True, null=True)),
                ('lease_generation', models.PositiveIntegerField(default=0)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pin')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'unique_together': {('submitter', 'client_item_id')},
            },
        ),
    ]
