# Generated by Django 2.2.28 on 2026-08-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_images", "0005_enforce_image_asset_metadata"),
        ("users", "0001_initial"),
        ("core", "0013_remove_pin_trashed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_asset",
                        to="django_images.Image",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.User",
                    ),
                ),
            ],
            options={
                "unique_together": {("submitter", "content_sha256")},
            },
        ),
    ]
