# Generated by Django 4.2.30 on 2026-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_board_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchimportitem',
            name='retryable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
