# Generated by Django 4.2.30 on 2026-09-11 07:11

from django.db import migrations, models


class RenameLegacyIndex(migrations.RenameIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if not self.allow_migrate_model(schema_editor.connection.alias, model):
            return
        columns = [model._meta.get_field(field).column for field in self.old_fields]
        names = schema_editor._constraint_names(
            model,
            column_names=columns,
            index=True,
            unique=False,
        )
        index = to_state.models[app_label, self.model_name_lower].get_index_by_name(
            self.new_name,
        )
        if not names:
            # Django 5.2의 신규 DB에는 과거 index_together 인덱스가 없을 수 있다.
            schema_editor.add_index(model, index)
            return
        if len(names) != 1:
            raise ValueError("보드의 기존 복합 인덱스를 하나로 식별할 수 없습니다.")
        if names[0] != self.new_name:
            schema_editor.rename_index(
                model, models.Index(fields=self.old_fields, name=names[0]), index,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_batchimportitem_retryable"),
    ]

    operations = [
        RenameLegacyIndex(
            model_name="board",
            new_name="board_owner_name_idx",
            old_fields=("submitter", "name"),
        ),
        RenameLegacyIndex(
            model_name="board",
            new_name="board_owner_order_id_idx",
            old_fields=("submitter", "display_order", "id"),
        ),
    ]
