version: "3.8"

services:
  pinry:
    image: ${PINRY_IMAGE}
    container_name: ${PINRY_CONTAINER_NAME}
    ports:
      - "${PINRY_HTTP_PORT}:80"
    volumes:
      - "${PINRY_DATA_PATH}:/data"
    restart: unless-stopped
