version: "3.8"

services:
  svrx-pinry:
    image: svrx-pinry:latest
    container_name: svrx-pinry
    ports:
      - "2048:80"
    volumes:
      - "/volume1/docker/svrx-pinry/data:/data"
    restart: unless-stopped
