# Generated by Django 2.2.28 on 2026-08-30 15:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_generation', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('lease_uuid', models.UUIDField()),
                ('state', models.CharField(choices=[('writing', 'writing'), ('closed', 'closed'), ('verifying', 'verifying'), ('published', 'published'), ('retiring', 'retiring'), ('cleaned', 'cleaned')], max_length=16)),
                ('relative_path', models.CharField(max_length=512)),
                ('dir_dev', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dir_ino', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dir_uid', models.PositiveIntegerField(blank=True, null=True)),
                ('dir_gid', models.PositiveIntegerField(blank=True, null=True)),
                ('dir_mode', models.PositiveIntegerField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportAttemptFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('archive', 'archive'), ('quarantine', 'quarantine')], max_length=16)),
                ('state', models.CharField(choices=[('writing', 'writing'), ('closed', 'closed'), ('verifying', 'verifying'), ('publishing', 'publishing'), ('ready_candidate', 'ready_candidate'), ('published', 'published'), ('retiring', 'retiring'), ('cleaned', 'cleaned')], max_length=16)),
                ('receipt_level', models.CharField(choices=[('open', 'open'), ('full', 'full')], default='open', max_length=8)),
                ('relative_path', models.CharField(max_length=512)),
                ('intent_relative_path', models.CharField(blank=True, max_length=512, null=True)),
                ('receipt_dev', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_ino', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_uid', models.PositiveIntegerField()),
                ('receipt_gid', models.PositiveIntegerField()),
                ('receipt_mode', models.PositiveIntegerField()),
                ('receipt_nlink', models.PositiveIntegerField()),
                ('receipt_size', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_mtime_ns', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_ctime_ns', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_sha256', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportBlob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_generation', models.UUIDField()),
                ('source_media_asset_id', models.PositiveIntegerField()),
                ('source_image_id', models.PositiveIntegerField()),
                ('source_relative_path', models.CharField(max_length=512)),
                ('expected_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('source_dev', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_ino', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_size', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_mtime_ns', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_ctime_ns', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('file_state', models.CharField(choices=[('writing', 'writing'), ('closed', 'closed')], default='writing', max_length=16)),
                ('part_relative_path', models.CharField(blank=True, max_length=512, null=True)),
                ('snapshot_relative_path', models.CharField(blank=True, max_length=512, null=True)),
                ('capture_method', models.CharField(blank=True, max_length=16, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_dev', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_ino', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_uid', models.PositiveIntegerField(blank=True, null=True)),
                ('receipt_gid', models.PositiveIntegerField(blank=True, null=True)),
                ('receipt_mode', models.PositiveIntegerField(blank=True, null=True)),
                ('receipt_nlink', models.PositiveIntegerField(blank=True, null=True)),
                ('receipt_mtime_ns', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_ctime_ns', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('cleanup_state', models.CharField(choices=[('pending', 'pending'), ('cleaned', 'cleaned'), ('blocked', 'blocked')], default='pending', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ExportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_position', models.PositiveIntegerField()),
                ('snapshot_generation', models.UUIDField()),
                ('pin_id', models.PositiveIntegerField()),
                ('pin_owner_id', models.PositiveIntegerField()),
                ('owner_username', models.CharField(max_length=150)),
                ('is_public', models.BooleanField()),
                ('published_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tags_json', models.TextField(default='[]')),
                ('source_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('source_url_redacted', models.BooleanField(default=False)),
                ('referer_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('referer_url_redacted', models.BooleanField(default=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('archive_image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('archive_xmp_path', models.CharField(blank=True, max_length=512, null=True)),
                ('inclusion_state', models.CharField(choices=[('included', 'included'), ('excluded', 'excluded')], default='included', max_length=16)),
                ('exclusion_reason', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ('target_position',),
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('pins', 'pins'), ('board', 'board')], max_length=8)),
                ('state', models.CharField(choices=[('archiving', 'archiving'), ('complete', 'complete'), ('expired', 'expired'), ('failed', 'failed'), ('queued', 'queued'), ('snapshotting', 'snapshotting'), ('verifying', 'verifying')], db_index=True, default='queued', max_length=16)),
                ('board_id_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('board_name_snapshot', models.CharField(blank=True, max_length=128, null=True)),
                ('board_private_snapshot', models.NullBooleanField()),
                ('board_owner_username_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('requested_total', models.PositiveIntegerField(default=0)),
                ('target_total', models.PositiveIntegerField(default=0)),
                ('snapshot_done', models.PositiveIntegerField(default=0)),
                ('archive_total', models.PositiveIntegerField(default=0)),
                ('archive_done', models.PositiveIntegerField(default=0)),
                ('included_total', models.PositiveIntegerField(default=0)),
                ('excluded_total', models.PositiveIntegerField(default=0)),
                ('excluded_not_visible_total', models.PositiveIntegerField(default=0)),
                ('excluded_permission_revoked_total', models.PositiveIntegerField(default=0)),
                ('bytes_total', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bytes_done', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('progress_at', models.DateTimeField(blank=True, null=True)),
                ('staging_cleanup_state', models.CharField(choices=[('pending', 'pending'), ('cleaned', 'cleaned'), ('blocked', 'blocked')], default='pending', max_length=16)),
                ('ready_cleanup_state', models.CharField(choices=[('absent', 'absent'), ('retained', 'retained'), ('pending', 'pending'), ('cleaned', 'cleaned'), ('blocked', 'blocked')], default='absent', max_length=16)),
                ('snapshot_generation', models.UUIDField(blank=True, null=True)),
                ('snapshot_relative_path', models.CharField(blank=True, max_length=512, null=True)),
                ('snapshot_dir_dev', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('snapshot_dir_ino', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('snapshot_dir_uid', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshot_dir_gid', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshot_dir_mode', models.PositiveIntegerField(blank=True, null=True)),
                ('candidate_snapshot_generation', models.UUIDField(blank=True, null=True)),
                ('candidate_snapshot_relative_path', models.CharField(blank=True, max_length=512, null=True)),
                ('candidate_snapshot_dir_dev', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('candidate_snapshot_dir_ino', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('candidate_snapshot_dir_uid', models.PositiveIntegerField(blank=True, null=True)),
                ('candidate_snapshot_dir_gid', models.PositiveIntegerField(blank=True, null=True)),
                ('candidate_snapshot_dir_mode', models.PositiveIntegerField(blank=True, null=True)),
                ('lease_uuid', models.UUIDField(blank=True, null=True)),
                ('worker_generation', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_generation', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('verifying_attempt_generation', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('verifying_size', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('verifying_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('verifying_completed_at', models.DateTimeField(blank=True, null=True)),
                ('resume_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, choices=[('invalid_target', 'invalid_target'), ('active_export_exists', 'active_export_exists'), ('export_not_ready', 'export_not_ready'), ('source_missing', 'source_missing'), ('source_changed', 'source_changed'), ('source_unsafe', 'source_unsafe'), ('snapshot_failed', 'snapshot_failed'), ('insufficient_space', 'insufficient_space'), ('archive_failed', 'archive_failed'), ('permission_changed', 'permission_changed'), ('all_items_revoked', 'all_items_revoked'), ('worker_repeated_failure', 'worker_repeated_failure'), ('export_worker_unavailable', 'export_worker_unavailable'), ('export_temporarily_unavailable', 'export_temporarily_unavailable'), ('export_storage_unsafe', 'export_storage_unsafe'), ('export_expired', 'export_expired')], max_length=64, null=True)),
                ('error_class', models.CharField(blank=True, choices=[('retryable', 'retryable'), ('operator_action_required', 'operator_action_required'), ('fatal', 'fatal')], max_length=32, null=True)),
                ('error_retryable', models.NullBooleanField()),
                ('ready_relative_path', models.CharField(blank=True, max_length=512, null=True)),
                ('ready_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ready_size', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ready_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('ready_dev', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ready_ino', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ready_uid', models.PositiveIntegerField(blank=True, null=True)),
                ('ready_gid', models.PositiveIntegerField(blank=True, null=True)),
                ('ready_mode', models.PositiveIntegerField(blank=True, null=True)),
                ('ready_nlink', models.PositiveIntegerField(blank=True, null=True)),
                ('ready_mtime_ns', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ready_ctime_ns', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ExportSlot',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('pin_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ExportWorkerLease',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('generation', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lease_uuid', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('health_state', models.CharField(choices=[('starting', 'starting'), ('ready', 'ready'), ('failed', 'failed'), ('stopped', 'stopped')], default='starting', max_length=16)),
                ('error_code', models.CharField(blank=True, choices=[('invalid_target', 'invalid_target'), ('active_export_exists', 'active_export_exists'), ('export_not_ready', 'export_not_ready'), ('source_missing', 'source_missing'), ('source_changed', 'source_changed'), ('source_unsafe', 'source_unsafe'), ('snapshot_failed', 'snapshot_failed'), ('insufficient_space', 'insufficient_space'), ('archive_failed', 'archive_failed'), ('permission_changed', 'permission_changed'), ('all_items_revoked', 'all_items_revoked'), ('worker_repeated_failure', 'worker_repeated_failure'), ('export_worker_unavailable', 'export_worker_unavailable'), ('export_temporarily_unavailable', 'export_temporarily_unavailable'), ('export_storage_unsafe', 'export_storage_unsafe'), ('export_expired', 'export_expired')], max_length=64, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='exportworkerlease',
            constraint=models.CheckConstraint(check=models.Q(id=1), name='export_worker_singleton'),
        ),
        migrations.AddConstraint(
            model_name='exportworkerlease',
            constraint=models.CheckConstraint(check=models.Q(generation__gte=0), name='export_worker_generation_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportworkerlease',
            constraint=models.CheckConstraint(check=models.Q(health_state__in=('starting', 'ready', 'failed', 'stopped')), name='export_worker_health_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportworkerlease',
            constraint=models.CheckConstraint(check=models.Q(('error_code__in', {'active_export_exists': ('retryable', True, '이미 진행 중인 내보내기가 있습니다.'), 'all_items_revoked': ('fatal', False, '내보낼 수 있는 Pin이 남지 않았습니다.'), 'archive_failed': ('retryable', True, 'ZIP 파일을 만들지 못했습니다.'), 'export_expired': ('fatal', False, '다운로드 기간이 만료됐습니다.'), 'export_not_ready': ('retryable', True, '아직 내보내기가 완료되지 않았습니다.'), 'export_storage_unsafe': ('operator_action_required', False, '내보내기 저장소를 안전하게 사용할 수 없습니다.'), 'export_temporarily_unavailable': ('retryable', True, '잠시 후 다시 시도하세요.'), 'export_worker_unavailable': ('retryable', True, '내보내기 작업자를 기다리고 있습니다.'), 'insufficient_space': ('operator_action_required', True, '내보내기에 필요한 저장 공간이 부족합니다.'), 'invalid_target': ('fatal', False, '내보낼 대상을 확인할 수 없습니다.'), 'permission_changed': ('fatal', False, '현재 권한으로 다시 내보내세요.'), 'snapshot_failed': ('retryable', True, '원본 스냅숏을 만들지 못했습니다.'), 'source_changed': ('retryable', True, '원본이 변경되어 내보내기를 중단했습니다.'), 'source_missing': ('fatal', False, '원본 파일을 찾을 수 없습니다.'), 'source_unsafe': ('operator_action_required', False, '원본 저장 상태를 확인해야 합니다.'), 'worker_repeated_failure': ('operator_action_required', True, '내보내기 작업자를 확인해야 합니다.')}), ('error_code__isnull', True), _connector='OR'), name='export_worker_error_valid'),
        ),
        migrations.AddField(
            model_name='exporttarget',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='exports.ExportJob'),
        ),
        migrations.AddField(
            model_name='exportslot',
            name='current_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exports.ExportJob'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportitem',
            name='blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exports.ExportBlob'),
        ),
        migrations.AddField(
            model_name='exportitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exports.ExportJob'),
        ),
        migrations.AddField(
            model_name='exportblob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blobs', to='exports.ExportJob'),
        ),
        migrations.AddField(
            model_name='exportattemptfile',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exports.ExportAttempt'),
        ),
        migrations.AddField(
            model_name='exportattempt',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exports.ExportJob'),
        ),
        migrations.AlterUniqueTogether(
            name='exporttarget',
            unique_together={('job', 'position'), ('job', 'pin_id')},
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['state', 'created_at', 'id'], name='export_fifo_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['owner', 'created_at'], name='export_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(scope__in=('pins', 'board')), name='export_job_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(state__in=('archiving', 'complete', 'expired', 'failed', 'queued', 'snapshotting', 'verifying')), name='export_job_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(snapshot_done__lte=django.db.models.expressions.F('target_total')), name='export_snapshot_total_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(archive_done__lte=django.db.models.expressions.F('archive_total')), name='export_archive_total_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(bytes_done__lte=django.db.models.expressions.F('bytes_total')), name='export_bytes_total_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(included_total=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('requested_total'), '-', django.db.models.expressions.F('excluded_total'))), name='export_included_total_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(('bytes_total__gte', 0), ('bytes_done__gte', 0), ('snapshot_dir_dev__gte', 0), ('snapshot_dir_ino__gte', 0), ('candidate_snapshot_dir_dev__gte', 0), ('candidate_snapshot_dir_ino__gte', 0), ('worker_generation__gte', 0), ('attempt_generation__gte', 0), ('verifying_attempt_generation__gte', 0), ('verifying_size__gte', 0), ('ready_size__gte', 0), ('ready_dev__gte', 0), ('ready_ino__gte', 0), ('ready_mtime_ns__gte', 0), ('ready_ctime_ns__gte', 0)), name='export_job_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(staging_cleanup_state__in=('pending', 'cleaned', 'blocked')), name='export_staging_cleanup_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(ready_cleanup_state__in=('absent', 'retained', 'pending', 'cleaned', 'blocked')), name='export_ready_cleanup_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(('error_code__in', {'active_export_exists': ('retryable', True, '이미 진행 중인 내보내기가 있습니다.'), 'all_items_revoked': ('fatal', False, '내보낼 수 있는 Pin이 남지 않았습니다.'), 'archive_failed': ('retryable', True, 'ZIP 파일을 만들지 못했습니다.'), 'export_expired': ('fatal', False, '다운로드 기간이 만료됐습니다.'), 'export_not_ready': ('retryable', True, '아직 내보내기가 완료되지 않았습니다.'), 'export_storage_unsafe': ('operator_action_required', False, '내보내기 저장소를 안전하게 사용할 수 없습니다.'), 'export_temporarily_unavailable': ('retryable', True, '잠시 후 다시 시도하세요.'), 'export_worker_unavailable': ('retryable', True, '내보내기 작업자를 기다리고 있습니다.'), 'insufficient_space': ('operator_action_required', True, '내보내기에 필요한 저장 공간이 부족합니다.'), 'invalid_target': ('fatal', False, '내보낼 대상을 확인할 수 없습니다.'), 'permission_changed': ('fatal', False, '현재 권한으로 다시 내보내세요.'), 'snapshot_failed': ('retryable', True, '원본 스냅숏을 만들지 못했습니다.'), 'source_changed': ('retryable', True, '원본이 변경되어 내보내기를 중단했습니다.'), 'source_missing': ('fatal', False, '원본 파일을 찾을 수 없습니다.'), 'source_unsafe': ('operator_action_required', False, '원본 저장 상태를 확인해야 합니다.'), 'worker_repeated_failure': ('operator_action_required', True, '내보내기 작업자를 확인해야 합니다.')}), ('error_code__isnull', True), _connector='OR'), name='export_error_code_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(('error_class__in', ('retryable', 'operator_action_required', 'fatal')), ('error_class__isnull', True), _connector='OR'), name='export_error_class_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('snapshot_dir_dev__isnull', False), ('snapshot_dir_gid__isnull', False), ('snapshot_dir_ino__isnull', False), ('snapshot_dir_mode__isnull', False), ('snapshot_dir_uid__isnull', False), ('snapshot_generation__isnull', False), ('snapshot_relative_path__isnull', False)), models.Q(('snapshot_dir_dev__isnull', True), ('snapshot_dir_gid__isnull', True), ('snapshot_dir_ino__isnull', True), ('snapshot_dir_mode__isnull', True), ('snapshot_dir_uid__isnull', True), ('snapshot_generation__isnull', True), ('snapshot_relative_path__isnull', True)), _connector='OR'), name='export_snapshot_receipt_full'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('candidate_snapshot_dir_dev__isnull', False), ('candidate_snapshot_dir_gid__isnull', False), ('candidate_snapshot_dir_ino__isnull', False), ('candidate_snapshot_dir_mode__isnull', False), ('candidate_snapshot_dir_uid__isnull', False), ('candidate_snapshot_generation__isnull', False), ('candidate_snapshot_relative_path__isnull', False)), models.Q(('candidate_snapshot_dir_dev__isnull', True), ('candidate_snapshot_dir_gid__isnull', True), ('candidate_snapshot_dir_ino__isnull', True), ('candidate_snapshot_dir_mode__isnull', True), ('candidate_snapshot_dir_uid__isnull', True), ('candidate_snapshot_generation__isnull', True), ('candidate_snapshot_relative_path__isnull', True)), models.Q(('candidate_snapshot_generation__isnull', False), ('candidate_snapshot_relative_path__isnull', False), ('candidate_snapshot_dir_dev__isnull', True), ('candidate_snapshot_dir_gid__isnull', True), ('candidate_snapshot_dir_ino__isnull', True), ('candidate_snapshot_dir_mode__isnull', True), ('candidate_snapshot_dir_uid__isnull', True)), _connector='OR'), name='export_candidate_snapshot_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('verifying_attempt_generation__isnull', False), ('verifying_completed_at__isnull', False), ('verifying_sha256__isnull', False), ('verifying_size__isnull', False)), models.Q(('verifying_attempt_generation__isnull', True), ('verifying_completed_at__isnull', True), ('verifying_sha256__isnull', True), ('verifying_size__isnull', True)), _connector='OR'), name='export_verifying_receipt_full'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ready_ctime_ns__isnull', False), ('ready_dev__isnull', False), ('ready_display_name__isnull', False), ('ready_gid__isnull', False), ('ready_ino__isnull', False), ('ready_mode__isnull', False), ('ready_mtime_ns__isnull', False), ('ready_nlink__isnull', False), ('ready_relative_path__isnull', False), ('ready_sha256__isnull', False), ('ready_size__isnull', False), ('ready_uid__isnull', False)), models.Q(('ready_ctime_ns__isnull', True), ('ready_dev__isnull', True), ('ready_display_name__isnull', True), ('ready_gid__isnull', True), ('ready_ino__isnull', True), ('ready_mode__isnull', True), ('ready_mtime_ns__isnull', True), ('ready_nlink__isnull', True), ('ready_relative_path__isnull', True), ('ready_sha256__isnull', True), ('ready_size__isnull', True), ('ready_uid__isnull', True)), _connector='OR'), name='export_ready_receipt_full'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(('verifying_sha256__isnull', True), ('verifying_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='export_verifying_sha_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(('ready_sha256__isnull', True), ('ready_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='export_ready_sha_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, state='complete'), models.Q(('completed_at__isnull', False), ('expires_at__isnull', False), ('ready_cleanup_state', 'retained'), ('ready_relative_path__isnull', False), ('error_class__isnull', True), ('error_code__isnull', True), ('error_retryable__isnull', True)), _connector='OR'), name='export_complete_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, state='failed'), models.Q(('error_class__isnull', False), ('error_code__isnull', False), ('error_retryable__isnull', False), models.Q(('pk__isnull', True), models.Q(('error_class', 'fatal'), ('error_code', 'source_missing'), ('error_retryable', False)), models.Q(('error_class', 'retryable'), ('error_code', 'source_changed'), ('error_retryable', True)), models.Q(('error_class', 'operator_action_required'), ('error_code', 'source_unsafe'), ('error_retryable', False)), models.Q(('error_class', 'retryable'), ('error_code', 'snapshot_failed'), ('error_retryable', True)), models.Q(('error_class', 'operator_action_required'), ('error_code', 'insufficient_space'), ('error_retryable', True)), models.Q(('error_class', 'retryable'), ('error_code', 'archive_failed'), ('error_retryable', True)), models.Q(('error_class', 'fatal'), ('error_code', 'permission_changed'), ('error_retryable', False)), models.Q(('error_class', 'fatal'), ('error_code', 'all_items_revoked'), ('error_retryable', False)), models.Q(('error_class', 'operator_action_required'), ('error_code', 'worker_repeated_failure'), ('error_retryable', True)), models.Q(('error_class', 'operator_action_required'), ('error_code', 'export_storage_unsafe'), ('error_retryable', False)), _connector='OR')), _connector='OR'), name='export_failed_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, state__in=('queued', 'snapshotting', 'archiving', 'verifying', 'failed')), ('ready_relative_path__isnull', True), _connector='OR'), name='export_active_ready_empty'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, state='expired'), models.Q(('ready_cleanup_state__in', ('pending', 'blocked')), ('ready_relative_path__isnull', False)), models.Q(('ready_cleanup_state', 'cleaned'), ('ready_relative_path__isnull', True)), _connector='OR'), name='export_expired_ready_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportitem',
            constraint=models.CheckConstraint(check=models.Q(inclusion_state__in=('included', 'excluded')), name='export_item_inclusion_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='exportitem',
            unique_together={('job', 'target_position'), ('job', 'pin_id')},
        ),
        migrations.AddConstraint(
            model_name='exportblob',
            constraint=models.CheckConstraint(check=models.Q(file_state__in=('writing', 'closed')), name='export_blob_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportblob',
            constraint=models.CheckConstraint(check=models.Q(cleanup_state__in=('pending', 'cleaned', 'blocked')), name='export_blob_cleanup_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportblob',
            constraint=models.CheckConstraint(check=models.Q(('source_dev__gte', 0), ('source_ino__gte', 0), ('source_size__gte', 0), ('source_mtime_ns__gte', 0), ('source_ctime_ns__gte', 0), ('size__gte', 0), ('receipt_dev__gte', 0), ('receipt_ino__gte', 0), ('receipt_mtime_ns__gte', 0), ('receipt_ctime_ns__gte', 0)), name='export_blob_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='exportblob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('receipt_ctime_ns__isnull', False), ('receipt_dev__isnull', False), ('receipt_gid__isnull', False), ('receipt_ino__isnull', False), ('receipt_mode__isnull', False), ('receipt_mtime_ns__isnull', False), ('receipt_nlink__isnull', False), ('receipt_uid__isnull', False), ('size__isnull', False)), models.Q(('receipt_ctime_ns__isnull', True), ('receipt_dev__isnull', True), ('receipt_gid__isnull', True), ('receipt_ino__isnull', True), ('receipt_mode__isnull', True), ('receipt_mtime_ns__isnull', True), ('receipt_nlink__isnull', True), ('receipt_uid__isnull', True), ('size__isnull', True)), _connector='OR'), name='export_blob_receipt_full'),
        ),
        migrations.AddConstraint(
            model_name='exportblob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, file_state='closed'), ('receipt_dev__isnull', False), _connector='OR'), name='export_blob_closed_receipt_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportblob',
            constraint=models.CheckConstraint(check=models.Q(('expected_sha256__isnull', True), ('expected_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='export_blob_expected_sha_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportblob',
            constraint=models.CheckConstraint(check=models.Q(('receipt_sha256__isnull', True), ('receipt_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='export_blob_receipt_sha_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='exportblob',
            unique_together={('job', 'snapshot_generation', 'source_media_asset_id')},
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(kind__in=('archive', 'quarantine')), name='export_attempt_file_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(state__in=('writing', 'closed', 'verifying', 'publishing', 'ready_candidate', 'published', 'retiring', 'cleaned')), name='export_attempt_file_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(receipt_level__in=('open', 'full')), name='export_attempt_file_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(('receipt_dev__gte', 0), ('receipt_ino__gte', 0), ('receipt_size__gte', 0), ('receipt_mtime_ns__gte', 0), ('receipt_ctime_ns__gte', 0)), name='export_attempt_file_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('receipt_ctime_ns__isnull', False), ('receipt_mtime_ns__isnull', False), ('receipt_size__isnull', False)), models.Q(('receipt_ctime_ns__isnull', True), ('receipt_mtime_ns__isnull', True), ('receipt_size__isnull', True)), _connector='OR'), name='export_attempt_file_receipt_full'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('receipt_ctime_ns__isnull', True), ('receipt_level', 'open'), ('receipt_mtime_ns__isnull', True), ('receipt_sha256__isnull', True), ('receipt_size__isnull', True)), models.Q(('receipt_ctime_ns__isnull', False), ('receipt_level', 'full'), ('receipt_mtime_ns__isnull', False), ('receipt_size__isnull', False)), _connector='OR'), name='export_attempt_file_level_receipt'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, state__in=('verifying', 'publishing', 'ready_candidate', 'published')), models.Q(('receipt_level', 'full'), ('receipt_sha256__isnull', False)), _connector='OR'), name='export_attempt_file_verified_receipt_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, state='closed'), ('receipt_level', 'full'), _connector='OR'), name='export_attempt_file_closed_receipt_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(models.Q(('kind', 'archive'), ('state', 'publishing')), models.Q(('kind', 'quarantine'), ('state', 'writing')), _connector='OR'), _negated=True), ('intent_relative_path__isnull', False), _connector='OR'), name='export_attempt_file_intent_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('state__in', ('ready_candidate', 'published', 'cleaned')), models.Q(('kind', 'quarantine'), ('state', 'closed')), _connector='OR'), _negated=True), ('intent_relative_path__isnull', True), _connector='OR'), name='export_attempt_file_final_intent_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, kind='quarantine'), ('state__in', ('writing', 'closed', 'cleaned')), _connector='OR'), name='export_quarantine_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattemptfile',
            constraint=models.CheckConstraint(check=models.Q(('receipt_sha256__isnull', True), ('receipt_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='export_attempt_file_sha_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='exportattemptfile',
            unique_together={('attempt', 'relative_path')},
        ),
        migrations.AddConstraint(
            model_name='exportattempt',
            constraint=models.CheckConstraint(check=models.Q(state__in=('writing', 'closed', 'verifying', 'published', 'retiring', 'cleaned')), name='export_attempt_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattempt',
            constraint=models.CheckConstraint(check=models.Q(('attempt_generation__gte', 0), ('dir_dev__gte', 0), ('dir_ino__gte', 0)), name='export_attempt_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='exportattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('dir_dev__isnull', False), ('dir_gid__isnull', False), ('dir_ino__isnull', False), ('dir_mode__isnull', False), ('dir_uid__isnull', False)), models.Q(('dir_dev__isnull', True), ('dir_gid__isnull', True), ('dir_ino__isnull', True), ('dir_mode__isnull', True), ('dir_uid__isnull', True)), _connector='OR'), name='export_attempt_dir_receipt_full'),
        ),
        migrations.AddConstraint(
            model_name='exportattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, state__in=('closed', 'verifying', 'published')), ('exported_at__isnull', False), _connector='OR'), name='export_attempt_exported_at_valid'),
        ),
        migrations.AddConstraint(
            model_name='exportattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, state='cleaned'), ('dir_dev__isnull', False), _connector='OR'), name='export_attempt_cleaned_receipt_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='exportattempt',
            unique_together={('job', 'attempt_generation')},
        ),
    ]
