# Generated by Django 4.2.30 on 2026-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0002_exporttarget_identity_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="board_private_snapshot",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="error_retryable",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
