# Generated by Django 4.2.30 on 2026-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_alter_exportjob_nullable_booleans'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exportjob',
            name='export_failed_state_valid',
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('state', 'failed'), _negated=True), models.Q(('error_class__isnull', False), ('error_code__isnull', False), ('error_retryable__isnull', False), models.Q(models.Q(('error_class', 'fatal'), ('error_code', 'source_missing'), ('error_retryable', False)), models.Q(('error_class', 'retryable'), ('error_code', 'source_changed'), ('error_retryable', True)), models.Q(('error_class', 'operator_action_required'), ('error_code', 'source_unsafe'), ('error_retryable', False)), models.Q(('error_class', 'retryable'), ('error_code', 'snapshot_failed'), ('error_retryable', True)), models.Q(('error_class', 'operator_action_required'), ('error_code', 'insufficient_space'), ('error_retryable', True)), models.Q(('error_class', 'retryable'), ('error_code', 'archive_failed'), ('error_retryable', True)), models.Q(('error_class', 'fatal'), ('error_code', 'permission_changed'), ('error_retryable', False)), models.Q(('error_class', 'fatal'), ('error_code', 'all_items_revoked'), ('error_retryable', False)), models.Q(('error_class', 'operator_action_required'), ('error_code', 'worker_repeated_failure'), ('error_retryable', True)), models.Q(('error_class', 'operator_action_required'), ('error_code', 'export_storage_unsafe'), ('error_retryable', False)), _connector='OR')), _connector='OR'), name='export_failed_state_valid'),
        ),
    ]
